"""Built-in translations; user paths, names and tags are never translated."""
from contextvars import ContextVar
language=ContextVar('language',default='en')
PAIRS={
'无效尺寸或坐标：':'Invalid size or coordinate: ',
'放大倍数必须是正整数':'The enlargement factor must be a positive integer.',
'倍数必须是正整数':'The factor must be a positive integer.',
'倍数必须为正整数':'The factor must be a positive integer.',
'质量倍数模式无效':'Invalid mass scaling mode.',
'找不到依赖资源：':'Dependency not found: ', '\n来自：':'\nReferenced by: ',
'已取消，原文件未修改':'Cancelled. Original files were not modified.',
'XML 循环引用：':'Circular XML reference: ', '不支持 DTD/ENTITY':'DTD/ENTITY is not supported.',
'几何 scale 必须为正数':'Geometry scale must be positive.',
'包含 voxscript 动态生成几何，无法保证静态等比放大；未导出':'Dynamic voxscript geometry cannot be enlarged reliably by this static exporter. No export was made.',
'找不到 VOX：':'VOX file not found: ', '放大体素：':'Enlarging voxels: ', '处理 XML：':'Processing XML: ',
'不支持的 vox file：':'Unsupported vox file: ', ' pos 超过三个分量':' pos has more than three components.',
'找不到引用 XML：':'Referenced XML not found: ',
'包含运行时生成几何的 voxscript，无法在保留脚本原文的同时保证等比放大，已停止导出':'Runtime voxscript geometry cannot be enlarged while preserving its original script. Export stopped.',
'XML 层级、name 或 tags 校验失败':'XML hierarchy, name or tag verification failed.',
'输出必须是 XML 文件名':'The output must be an XML filename.',
'请在原 XML 所在文件夹内输出':'Save the output in the same folder as the source XML.',
'不能覆盖原 XML，请使用新文件名':'The original XML cannot be overwritten. Choose a new filename.',
'输出已存在，请使用新文件名：':'Output already exists. Choose a new filename: ',
'输出已存在：':'Output already exists: ',
'检查 XML 层级、原 scale 和引用…':'Checking XML hierarchy, scales and references...',
'处理镜像与层级旋转…':'Processing reflection and hierarchy transforms...',
'镜像保留原几何 scale':'Mirroring preserves the original geometry scale',
'新旧 VOX 引用隔离校验失败':'VOX reference isolation verification failed.',
'处理期间原 XML 已改变，已取消导出':'The source XML changed during processing. Export cancelled.',
'处理期间引用资源已改变：':'A referenced resource changed during processing: ',
'原脚本未修改；检测到 TABS 且启用参数调整时，会生成车辆脚本及其 include 副本。其他脚本仍引用原文件。':'Original scripts are unchanged. TABS vehicle scripts and their includes are copied when parameter scaling is enabled; other scripts retain their original references.',
'TABS 全局框架中的弹道孔径上限、速度和其他运行时常量不由车辆副本控制，游戏行为仍需验证。':'Global TABS ballistic limits and other runtime constants are outside the vehicle copy. In-game behavior still requires verification.',
'灯光 scale 原样保留。':'Light scale is preserved. ',
'镜像保留原几何 scale。':'Mirroring preserves geometry scale. ',
'整数 scale 乘积通过复制体素实现；小数乘积写入 XML scale，不重复复制体素。':'Integer scale products replicate voxels; fractional products use XML scale without duplicate replication. ',
'碰撞与破坏仍需实际游戏验证。':'Collision and destruction still require in-game testing.',
'镜像标签保留检查失败':'Mirror tag preservation verification failed.',
'镜像体素：':'Mirroring voxels: ',
'TABS 标签 ':'TABS tag ', ' 不是数值：':' is not numeric: ',
'Lua 表括号不匹配':'Mismatched Lua table braces.', 'Lua 表括号未闭合':'Unclosed Lua table braces.',
'需要读取 TABS 的 TABS/scripts/ammo.lua，才能放大内置弹药预设。请填写正确的游戏目录。':'TABS/scripts/ammo.lua is needed to scale built-in ammunition. Select the correct Teardown installation folder.',
'TABS shellTypes 格式无法识别，已停止避免漏改弹药':'Unrecognized TABS shellTypes format. Export stopped to avoid incomplete ammunition scaling.',
'TABS 弹药预设不存在，未导出：':'TABS ammunition preset not found. Export stopped: ',
'弹药预设包含无法静态复制的表达式：':'An ammunition preset contains an expression that cannot be copied statically: ',
'Lua include 循环引用：':'Circular Lua include: ', 'Lua include 不存在：':'Lua include not found: ',
'核对体素与材质：':'Verifying voxels and materials: ',
'无效 VOX 文件':'Invalid VOX file.', 'VOX 块头损坏':'Corrupt VOX chunk header.',
'VOX 数据截断':'Truncated VOX data.',
'暂不支持带嵌套子块的 VOX 数据，已停止导出':'Nested VOX chunks are not supported. Export stopped.',
'VOX 长度不匹配':'VOX length mismatch.', '模型体素画布过大或尺寸无效':'Voxel canvas is too large or its dimensions are invalid.',
'TDCZ 解压尺寸不匹配':'TDCZ decompressed size mismatch.', 'XYZI 长度无效':'Invalid XYZI length.',
'XYZI 坐标超出 SIZE':'XYZI coordinates exceed SIZE.', 'VOX 没有可读取的模型':'No readable models in VOX.',
'无法唯一解析 VOX object=':'Cannot uniquely resolve VOX object=', '，已停止避免错位':'; stopped to prevent misalignment.',
'所选 VOX 对象没有实体体素':'The selected VOX object has no occupied voxels.',
'所选 VOX 对象含多帧变换，暂不能保证静态放大精度':'The selected VOX has animated transforms; static enlargement cannot preserve them reliably.',
' 放大后单个画布超过 20 亿体素；请降低倍数':' would exceed two billion voxels in one canvas. Reduce the factor.',
'动画模型各帧旋转中心不同，暂不能安全放大':'Animated frames have different pivots and cannot be enlarged safely.',
'无场景图的多模型 VOX 无法确定布局':'Cannot determine the layout of multiple VOX models without a scene graph.',
'无场景图的多模型 VOX 不能确定布局':'Cannot determine the layout of multiple VOX models without a scene graph.',
'VOX 场景图循环引用':'Circular VOX scene graph.', 'VOX 场景图损坏或循环引用':'Corrupt or circular VOX scene graph.',
'VOX 含动画帧，不能按静态几何安全改写':'Animated VOX frames cannot be safely rewritten as static geometry.',
'VOX 平移不是三个整数':'VOX translation must contain three integers.',
'VOX shape 含多帧模型，不能静态改写':'VOX shape has multiple frames and cannot be rewritten statically.',
'VOX 引用了不存在的模型':'VOX references a missing model.', 'VOX 找不到对象：':'VOX object not found: ',
'可见场景':'visible scene', 'VOX 对象没有实体体素':'The VOX object has no occupied voxels.',
'放大后的单个部件超过 20 亿体素':'An enlarged part exceeds two billion voxels.',
'voxbox size 超过三个分量':'voxbox size has more than three components.', '无效 voxbox size：':'Invalid voxbox size: ',
}
EN_ZH={
'Mirror axis must be X, Y or Z':'镜像轴必须为 X、Y 或 Z',
'Output must not overwrite source XML':'输出不能覆盖原 XML',
'DTD/entities are not supported':'不支持 DTD/实体',
'Instance XML not found: ':'找不到实例 XML：', 'Recursive instance cycle: ':'实例循环引用：',
'Instance cycle skipped: ':'已跳过实例循环引用：',
'Joint positions are reflected; motor directions and angle limits need in-game verification.':'关节位置已镜像；马达方向和角度限制需要在游戏中验证。',
'Wheel positions are reflected; steering and suspension behavior need in-game verification.':'车轮位置已镜像；转向和悬挂行为需要在游戏中验证。',
'Runtime voxscript geometry is not baked or reflected by this static XML tool.':'本静态工具不会烘焙或镜像 voxscript 在运行时生成的几何。',
'Lua code and runtime-created geometry are unchanged; verify scripted behavior in-game.':'Lua 代码和运行时生成的几何保留；脚本行为需要在游戏中验证。',
'Tag verification failed; mirrored XML was not accepted':'标签校验失败，未接受镜像 XML',
'Source XML is inside the output assets directory':'原 XML 位于输出资源目录内',
'Cannot safely resolve VOX object pivot: ':'无法安全解析 VOX 对象原点：',
'VOX pivot metadata failed: ':'VOX 原点元数据错误：',
'Invalid VOX MAIN length: ':'VOX MAIN 长度无效：', 'Truncated VOX chunk':'VOX 块数据截断',
'Invalid VOX XYZI voxel count':'VOX XYZI 体素数量无效', 'Invalid VOX chunk alignment':'VOX 块对齐无效',
'Invalid VOX signed-permutation code: ':'VOX 方向编码无效：',
'Invalid uncompressed VOX dimensions: ':'未压缩 VOX 尺寸无效：',
'No readable XYZI data in VOX (compressed/unsupported file): ':'VOX 没有可读取的 XYZI 数据（压缩或不支持）：',
'VOX SIZE without XYZI':'VOX SIZE 缺少 XYZI', 'VOX XYZI without SIZE':'VOX XYZI 缺少 SIZE',
'VOX voxel lies outside SIZE':'VOX 体素超出 SIZE', 'XYZI dimensions exceed byte coordinates':'XYZI 尺寸超过字节坐标范围',
}
def tr(value):
    return PAIRS.get(value,value) if language.get()=='en' else EN_ZH.get(value,value)
def choose(en,zh):return en if language.get()=='en' else zh
def set_language(value):
    if value not in ('en','zh'):raise ValueError('Language must be en or zh')
    language.set(value)
